version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - ta3-networks
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ta13db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  ta-13:
    build: .
    container_name: ta-13-2023
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - ta3-networks
    ports:
      - "3000:3000"
    volumes:
      - ./.env.production:/app/.env.production
    restart: always
    entrypoint: bash -c "ENV=PROD ./application"
networks:
  ta3-networks:
volumes:
  db_data:
  app:
