basePath: /
definitions:
  collections.ResponseGetCollections:
    properties:
      collections:
        items:
          $ref: '#/definitions/entity.Collection'
        type: array
    type: object
  entity.Collection:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  entity.User:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  user.ResponseGetUsers:
    properties:
      users:
        items:
          $ref: '#/definitions/entity.User'
        type: array
    type: object
  user.ResponseHello:
    properties:
      message:
        type: string
    type: object
host: localhost:9000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Dokumentasi API D4 TRPL 19 TA 13.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API TA
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/user.ResponseHello'
      summary: Get hi
      tags:
      - hai
  /collections:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/collections.ResponseGetCollections'
      summary: Get all collections
      tags:
      - Collections
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/user.ResponseGetUsers'
      summary: Get all users
      tags:
      - User
swagger: "2.0"
