name: Development CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: cd /home/ubuntu/ta/backend && git pull origin master && sudo docker compose up --build -d
        env:
          CI: true
